USE QLSV
GO

-- 5.1
CREATE FUNCTION svInKhoa (@MASV VARCHAR(10), @MAKHOA VARCHAR(10))
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @LOP VARCHAR(10)
	SELECT @LOP = MALOP FROM SINHVIEN WHERE MASV = @MASV
	DECLARE @KHOA VARCHAR(10)
	SELECT @KHOA = MAKHOA FROM LOP WHERE MALOP = @LOP
	DECLARE @KQ CHAR(5) = 'FALSE'
	IF(@KHOA = @MAKHOA) SET @KQ = 'TRUE'
	RETURN @KQ
END
GO

--SELECT dbo.svInKhoa('212003','CNTT')


-- 5.2

CREATE FUNCTION diemSauCung (@MASV VARCHAR(10), @MAMON VARCHAR(10))
RETURNS FLOAT
AS
BEGIN
	DECLARE @RESULT FLOAT = 0 
	DECLARE @LANTHIMAX INT
	SELECT @LANTHIMAX = MAX(LANTHI) FROM KETQUA WHERE MASV = @MASV AND MAMH = @MAMON GROUP BY (MAMH)
	SELECT @RESULT = DIEM FROM KETQUA WHERE MASV = @MASV AND MAMH = @MAMON AND LANTHI = @LANTHIMAX
	RETURN @RESULT
END
GO

--SELECT	dbo.diemSauCung('212001','THT01')

-- 5.3
CREATE FUNCTION tinhDiemTB(@MASV VARCHAR(10))
RETURNS FLOAT
AS
BEGIN
	DECLARE @RESULT FLOAT = 0
	SELECT @RESULT = AVG(DIEM) FROM KETQUA WHERE MASV = @MASV AND DIEM = (SELECT dbo.diemSauCung(@MASV,MAMH))
	RETURN @RESULT
END
GO

--SELECT * FROM KETQUA WHERE MASV = '212001'
--SELECT dbo.tinhDiemTB('212001')


-- 5.4
CREATE FUNCTION traDiemVaLanThi(@MASV VARCHAR(10),@MAMH VARCHAR(10))
RETURNS TABLE
AS RETURN (SELECT LANTHI, DIEM FROM KETQUA WHERE MASV = @MASV AND MAMH = @MAMH)
GO

--SELECT * FROM dbo.traDiemVaLanThi('212001','THT01')

-- 5.5
CREATE FUNCTION monPhaiHoc(@MASV VARCHAR(10))
RETURNS TABLE
AS RETURN (SELECT * FROM MONHOC WHERE MAKHOA = (SELECT MAKHOA FROM LOP WHERE MALOP = (SELECT MALOP FROM SINHVIEN WHERE MASV = @MASV)))
GO

--SELECT * FROM dbo.monPhaiHoc('212001')