USE QLSV
GO

-- 6.1
CREATE PROC showSV @MALOP VARCHAR(10)
AS
BEGIN
	SELECT * FROM SINHVIEN WHERE MALOP = @MALOP
END
GO

--EXEC showSV 'TH2002/01'

-- 6.2
CREATE PROC svDiemCaoHon @MASV1 VARCHAR(10), @MASV2 VARCHAR(10), @MAMH VARCHAR(10) ,@SVCAOHON VARCHAR(10) OUTPUT
AS
BEGIN
	DECLARE @DIEM1 FLOAT
	DECLARE @DIEM2 FLOAT
	SELECT @DIEM1 = DIEM FROM KETQUA WHERE MAMH = @MAMH AND MASV = @MASV1 AND LANTHI = 1
	SELECT @DIEM2 = DIEM FROM KETQUA WHERE MAMH = @MAMH AND MASV = @MASV2 AND LANTHI = 1
	IF(@DIEM1 > @DIEM2) SET @SVCAOHON = @MASV1 ELSE SET @SVCAOHON = @MASV2
END
GO

--DECLARE @SVCAOHON VARCHAR(10)
--EXEC svDiemCaoHon '212001', '212003','THT01', @SVCAOHON OUTPUT
--PRINT @SVCAOHON

-- 6.3
